version: '3.8'

services:
  # uncomment this out to use postgres via the postgres image instead of local instance
  # db:
  #   image: postgres:13.4
  #   environment:
  #     - POSTGRES_DB=ent-starter
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     # not ideal but it's all local and the quickest way I could get it to work
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   volumes:
  #      #  feel free to update to store the data in a different location
  #     - ./postgres_data/db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: develop.Dockerfile
        # change to name of your app
    container_name: ent-starter
    ports:
      - 4000:4000
      - 9229:9229 # for debugger
    volumes:
      - .:/app:rw,delegated
    environment:
    # postgres on local machine
    - DB_CONNECTION_STRING=postgres://ola:@host.docker.internal/ent-starter
    # postgres docker image
    # - DB_CONNECTION_STRING=postgres://postgres:postgres@db/ent-starter
    # local sqlite file
    #- DB_CONNECTION_STRING=sqlite:///ent-starter.db
