// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { NodeType } from "./const";
import { loadEnt, ID, Viewer, Ent, LoadEntOptions } from "@lolopinto/ent";
import { User } from "src/ent/internal";

export async function loadEntByType(
  viewer: Viewer,
  type: NodeType,
  id: ID,
): Promise<Ent | null> {
  return loadEnt(viewer, id, getLoaderOptions(type));
}

export function getLoaderOptions(type: NodeType): LoadEntOptions<Ent> {
  switch (type) {
    case NodeType.User:
      return User.loaderOptions();
  }
}
